package corbaBanque;

/**
 * corbaBanque/IBanqueRemote.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Banque.idl mercredi 1 décembre 2021 08 h 51
 * WAT
 */

public interface IBanqueRemote extends IBanqueRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface IBanqueRemote
